version: '3.8'

services:
  # Main Streamlit application
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ~/.config/gcloud:/root/.config/gcloud  # For Google Drive credentials
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - EXA_API_KEY=${EXA_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_APP_ID=${GOOGLE_APP_ID}
      - QDRANT_DB_URL=http://qdrant:6333
    depends_on:
      - qdrant
      - gdrive-picker
    networks:
      - deepseek-network

  # Google Drive Picker service
  gdrive-picker:
    build:
      context: .
      dockerfile: google_drive_picker/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./google_drive_picker:/app/google_drive_picker
      - ./google_drive_popup.html:/app/google_drive_popup.html
    networks:
      - deepseek-network

  # Qdrant vector database
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - deepseek-network

networks:
  deepseek-network:
    driver: bridge

volumes:
  qdrant_storage:
    driver: local
