version: '3.8'

services:
  # Main Streamlit application with development settings
  streamlit:
    volumes:
      - .:/app  # Mount the entire project directory
    environment:
      - PYTHONUNBUFFERED=1  # Ensure Python output is not buffered
    command: ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.runOnSave=true"]

  # Google Drive Picker service with development settings
  gdrive-picker:
    volumes:
      - ./google_drive_picker:/app/google_drive_picker  # Mount the picker directory
      - ./serve_picker.py:/app/serve_picker.py  # Mount the server file
      - ./google_drive_popup.html:/app/google_drive_popup.html  # Mount the popup HTML
    command: ["python3", "serve_picker.py", "--serve-only", "--port", "3001"]
